# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ping1s < Formula
  desc "Now you can use ping1s, you can learn an ancient poem in 1 second, isn't it interesting!"
  homepage "https://github.com/youtiaoguagua/ping1s"
  version "1.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://ghproxy.com/https://github.com/youtiaoguagua/ping1s/releases/download/v1.4.3/ping1s_1.4.3_darwin_amd64.tar.gz"
      sha256 "98b56c879c95b0b383156d898b0559218b19b22d916dfcf2d4dda147af7d3b40"

      def install
        bin.install "ping1s"
      end
    end
    if Hardware::CPU.arm?
      url "https://ghproxy.com/https://github.com/youtiaoguagua/ping1s/releases/download/v1.4.3/ping1s_1.4.3_darwin_arm64.tar.gz"
      sha256 "e0c03e666c91fef2a79c9fbd859c3a02e1b5159c51ce2831b23d3ed507096166"

      def install
        bin.install "ping1s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://ghproxy.com/https://github.com/youtiaoguagua/ping1s/releases/download/v1.4.3/ping1s_1.4.3_linux_amd64.tar.gz"
      sha256 "ff323ab7852654ebe498edf8375ffe3563d2f0477d4503632cd45ddd9b623c62"

      def install
        bin.install "ping1s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://ghproxy.com/https://github.com/youtiaoguagua/ping1s/releases/download/v1.4.3/ping1s_1.4.3_linux_arm64.tar.gz"
      sha256 "11716e2986ac45fb76cd8e61c995d3890ceaa8d4f22a1ad5c02ae14637a7a853"

      def install
        bin.install "ping1s"
      end
    end
  end
end
